name = "Create Aeronoutics Multi"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c501663d631a5c28cb03247e5da6730d88e8845baab57cf76404f9b239613ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
