name = "Create Aeronoutics Multi"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02644aeb40b779df45d05144344a8073cd7e98b527d50e12c1fdf2c8f2ad9d9e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
